export const DeliveryInfo = [
    {
        username: 'user',
        firstName: '',
        lastName: '',
        phoneNumber: '',
        postCode: '',
        Address1: '',
        Address2: '',
        townCity: '',
        county: '',
    },
    {
        username: '123',
        firstName: '',
        lastName: '',
        phoneNumber: '',
        postCode: '',
        Address1: '',
        Address2: '',
        townCity: '',
        county: '',
    },
    {
        username: 'abc@123.lol',
        firstName: '',
        lastName: '',
        phoneNumber: '',
        postCode: '',
        Address1: '',
        Address2: '',
        townCity: '',
        county: '',
    },

]
