export const ItemList = [
    {
        itemId: 1,
        itemName: 'MNR',
        itemType: 'Switch Games',
        itemPrice: 400,
        itemQuantity: 500,
        itemDescription: 'Monster Hunter Rise JP for Switch',
        itemImage: 'https://images-na.ssl-images-amazon.com/images/I/91AqHZOHPhL._AC_SL1500_.jpg',
        itemChecked: false,
        attemptQuantity: 0,
        limitedQuantity: 5,
    },
    {
        itemId: 2,
        itemName: '3080',
        itemType: 'Display Card',
        itemPrice: 8000,
        itemQuantity: 20,
        itemDescription: 'Nvidia RTX 3080 Graphics Card',
        itemImage: 'https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ampere/rtx-3080/images/design/geforce-rtx-3080-4-960.jpg',
        itemChecked: false,
        attemptQuantity: 0,
        limitedQuantity: 2,
    },
    {
        itemId: 3,
        itemName: 'PS5',
        itemType: 'Console',
        itemPrice: 4000,
        itemQuantity: 10,
        itemDescription: 'Sony Playstation 5 Console Disk Version',
        itemImage: 'https://images-na.ssl-images-amazon.com/images/I/71PMC4DWWFL._AC_SL1500_.jpg',
        itemChecked: false,
        attemptQuantity: 0,
        limitedQuantity: 2,
    },

]